### PR TITLE
Ross/feature/redux toolkit stuff

### PR DESCRIPTION
**Pull request by RossaMania**
# Description
This PR implements a comprehensive authentication system using Redux Toolkit and Supabase, along with a restructured layout system leveraging Next.js 14's built-in layout capabilities. The changes establish proper user role management, protected routes, and improved state management across the application.

## Related to the following Jira/Trello issue 
- Routing.
- Interface stuff???
- Authentication.

## Main changes explained:
Implemented Redux Toolkit with dedicated slices for authentication and user management
Created AuthProvider component to centralize authentication logic and session management
Restructured layouts using Next.js 14 route-based system:

Moved layouts to appropriate route segments (src/app/user/layout.js and src/app/admin/layout.js)
Implemented proper authentication checks at layout level
Added dynamic routing with user IDs

Integrated Supabase authentication:

Added Google OAuth support
Implemented email/password authentication
Added proper session refresh and cleanup

Enhanced error handling and loading states across authentication flow
Removed redundant code:

Deleted unused useAuth and initializeAuth utilities
Removed unnecessary clientLogout function
Consolidated authentication logic into AuthProvider

## How to test:
Check out the Ross/feature/redux-toolkit-stuff branch
Run npm install to get new dependencies
Run npm run dev to start the development server
Test authentication flows:

Sign up with email/password at /signup
Verify admin authentication at /admin/login

Verify protected routes:
Attempt accessing /user/[id]/* routes while logged out
Attempt accessing /admin/[id]/* routes without admin privileges

Test session persistence:
Refresh the page while authenticated

Verify layouts:
Verify proper role-based navigation

## Screenshots or videos of changes:
Styled up the app with basic Bootstrap components and Flex.
image
URL changes!
image
Information displaying properly! Address works! 
image
Error right in a returning div!
image

## Note:
Are you able to look into any of this stuff as you work on interfaces? I would have spent a bit more time on it, but I didn't want to wreck interface stuff.
- There is still a bug somehow in /signup page. Something with the returning JSX? I think it's something with a div somewhere.
- I had trouble fixing merge conflicts. My Merge Editor locked up, and GitHub CoPilot tried to do some resolution stuff that I tried to cancel? So I fixed the /signup form the best I could. I even went on previous pull requests to get a previous version of the form. It has something to do with the <div> elements! I even eliminated unnecessary redundant header and footer components in the form to prevent double headers and navbars from rendering.
- Some troubleshooting steps: Add console.log statements in AuthProvider's initializeAuth function and Redux auth slice to trace the exact flow of auth state changes. Test a clean signup flow in an incognito window, watching both Network tab and Console to verify: Supabase auth endpoint responses, Redux state updates, Navigation triggers. Verify if clearSession is being called inadvertently by adding logs around all dispatch calls and auth subscription events in AuthProvider.
- The auth flow now properly coordinates between Supabase, Redux, and Next.js navigation.
- There's ongoing auth state persistence issues (/signup form).
- Some debugging console logs are currently present for auth state tracking.
- Additional work needed to resolve layout duplication edge cases.

### CODE REVIEW

**Review by garysmith1933 — CHANGES_REQUESTED** [review]
I have some questions about changes you made here, on top of that there is alot to review. Let me know when you are free to discuss this further.

**Comment by RossaMania** [comment]
> I have some questions about changes you made here, on top of that there is alot to review. Let me know when you are free to discuss this further.

Happy to help! So like a code review meeting?

**Comment by RossaMania** [comment]
As of this writing, it's about 12:25PM CST. I am still finishing up chores.

I'm happy to meet! 

Does something like around 1PM CST work for you? Maybe a few minutes after?

**Comment by garysmith1933** [comment]
> > I have some questions about changes you made here, on top of that there is alot to review. Let me know when you are free to discuss this further.
> 
> Happy to help! So like a code review meeting?



> As of this writing, it's about 12:25PM CST. I am still finishing up chores.
> 
> I'm happy to meet!
> 
> Does something like around 1PM CST work for you? Maybe a few minutes after?

Yes, just let me know when youre free in the discord.

**Comment by RossaMania** [comment]
Closing this PR following our productive code review discussion in Sprint 5.

Key technical decisions & scope clarification:
- Simplified application scope: focusing on manageable appointment volume and storage.
- Removing redundant caching layer: Supabase will handle data caching instead of implementing Redux Toolkit.
- We identified layout page issues causing metadata conflicts between server/client components (My fault).
- Agreed to remove unnecessary complexity from NextJS 14 nested layouts implementation.

Path forward:
- We chose a different approach by creating new branch with streamlined architecture.
- Team split:
  - Residential features and site styling.
  - Admin user functionality and backend/database work.

Thanks again to Gary for the thorough review and collaborative discussion!

Note: Original PR served as valuable exploration of NextJS 14 nested layout and metadata object features and helped surface important architectural decisions for the project.

**Pull request closed without merging**
